In [46]:
import numpy as np
from jinja2.ext import do
from numpy.ma.core import dot

In [45]:
# 定义向量
x=np.array([1,2,3])
print(x)
x.shape

[1 2 3]


(3,)

In [8]:
# 向量转制
x.T

array([1, 2, 3])

In [11]:
# 定义二维
y=np.array([[1,2,3]])
print(y)
y.shape

[[1 2 3]]


(1, 3)

In [21]:
# 相加
z=np.array([7,8,9])
print(z+x)
(z+x).shape

[ 8 10 12]


(3,)

In [23]:
# 向量相乘  对应位置相互乘
print(z * x)

[ 7 16 27]


In [30]:
# 点乘
print(x.dot(z))
print(np.dot(x,z))
print(x @ z)

50
50
50


In [33]:
# 计算范数
lo_norm=np.linalg.norm(x,ord=0) #L 0 范式
print(lo_norm)

l2_norm=np.linalg.norm(x,ord=2) #L 2范式
print(l2_norm)

3.0
3.7416573867739413


In [44]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print((a.shape))
print((a * b))
print(np.dot([1,2],[3,4]))
print(a@b)

(2, 2)
[[ 5 12]
 [21 32]]
11
[[19 22]
 [43 50]]


In [42]:
# 向量化
# a=[[1,2],[3,4]]
print(np.sum(a))
print(a.flatten())  #行向量化

10
[1 2 3 4]
