In [4]:
import numpy as np

In [7]:
# 随机生成（0，1）均匀分布的数
a=np.random.rand(5)
print(a)

[0.08569341 0.90377472 0.17042867 0.39392629 0.2814938 ]


In [9]:
b=np.random.rand(2,3)
print(b)

[[0.11693771 0.59800148 0.78283457]
 [0.33157562 0.66310571 0.47459612]]


In [22]:
# 随机生成（0，100）2行3列的矩阵
c=np.random.randint(0,100,size=(2,3))
print(c)

[[46 83 70]
 [ 7 17 30]]


In [25]:
#随机生成服从标准正态分布的数  均值为0，标准差为1，方差为1
d=np.random.randn(2,3)
print(d)
print((d+3)*10)

[[ 0.0704121  -0.55512344  0.82382493]
 [-0.1059561  -1.0861767  -2.43445258]]
[[30.704121   24.44876562 38.23824935]
 [28.940439   19.138233    5.65547418]]
